ci-cd test

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -52,5 +52,29 @@ jobs:  # ✅ jobs must be at the top level (no indentation under "on:")
           chmod +x scripts/build.sh
           scripts/build.sh
 
-      - name
+      - name: Start and check ROS 2 nodes
+        run: |
+          chmod +x scripts/run.sh
+          ./scripts/run.sh &
+          sleep 15
+
+          source /opt/ros/jazzy/setup.bash
+          EXPECTED_NODES="/heartbeat_monitor.py"
+          NODE_LIST=$(ros2 node list)
+          echo "$NODE_LIST"
+
+          for NODE in $EXPECTED_NODES; do
+            if [[ ! "$NODE_LIST" =~ "$NODE" ]]; then
+              echo "ERROR: $NODE node not found"
+              pkill -f run.sh || true
+              exit 1
+            fi
+          done
+
+          echo "✅ All nodes successfully launched."
+          echo "Killing ROS 2 nodes..."
+          pkill -f ros2 || true
+
+      - name: Success
+        run: echo "✅ Success!"
 
